- name: install nginx
  hosts: all
  become: yes # equal to -b in adhoc command(getting root access)
  tasks:
  -name: update cache
    dnf:
      update_cache: yes
  - name: installing nginx
    dnf:
      name: nginx
      state: installed
  - name: enable service
    service:
      name: nginx
      state: started
      enable: yes