- name: install nginx
  hosts: localhost
  become: yes # equal to -b in adhoc command(getting root access)
  tasks:
  -name: update cache
    yum:
      update_cache: yes
  - name: installing nginx
    yum:
      name: nginx
      state: installed
  - name: enable service
    service:
      name: nginx
      state: started
      enable: yes