- name: install nginx
  hosts: all
  become: yes # equal to -b in adhoc command(getting root access)
  tasks:
  - name: installing nginx
    dnf:
      name: nginx
      state: installed
    service:
      name: nginx
      state: started
      enable: yes