---
- name: vars called from vars.yml
  hosts: localhost
  vars:
    - vars.yml
  tasks:
   - name: variables decleared in vars.yml
      ansible.builtin.debug:
        msg: "My name is {{firstname}} {{name}}{{lastname}} and age is {{age}}"