- name: Number is greater than or equal to 10
  hosts: localhost
  vars_prompt:
  - name: Number
    prompt: Please enter a number
    private: no
  tasks:
  - name: number is less than 10
    ansible.builtin.debug:
      msg: "{{Number}} is less than 10"
    when: Number | int < 10 #  | int (builtin filter to change given prompt as integer )
  - name: number is greater than 10
    ansible.builtin.debug:
      msg: "{{Number}} is greater than or equal to 10"
    when: Number | int >= 10
