---
- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "I want tp print my name for this variable{{name | default ('Sathish Reddy')}}"