---
- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "I want to print my name for this variable{{name | default (' Sathish Reddy')}}"
- name: upper case
  hosts: localhost
  vars: 
    name: Ambati Sathish
  tasks:
  - name: print given text in upper case
    ansible.builtin.debug:
      msg: "{{name | upper}}"
- name: lower case
  hosts: localhost
  vars:
    name: Ambati Sathish
  tasks:
  - name: print given text in lower case
    ansible.builtin.debug:
      msg: "{{name | lower}}"
  
- name: remove duplicates
  hosts: localhost
  vars:
    number: [ 1, 2, 3, 2, 4, 5, 1]
  tasks:
  - name: print unique numbers
    ansible.builtin.debug:
      msg: "{{number | unique}}"
