---
- name: installing packages
  hosts: localhost
  become: yes
  tasks:
  - name: installing
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
    loop:
      - mysql
      - postfix
      - nginx

- name: installing packages
  hosts: localhost
  become: yes
  tasks:
  - name: installing
    ansible.builtin.dnf:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
      - {name: mysql, state: present}
      - {name: postfix, state: absent}
      - {name: nginx, state: absent}