---
- name: installing packages
  hosts: localhost
  become: yes
  tasks:
  - name: installing
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
    loop:
      - mysql
      - postfix
      - nginx