---
- name: data types
  hosts: web
  vars:
    course: Devops with allows #String
    tools: #list
    - linux
    - shell
    - ansible
    experience: #map
     Devops: 2 #number
     AWS: 2
     docker: 1
    RealProject: true #boolean
  tasks: 
  - name: printing variables
    debug:
      msg: "{{course}},{{tools}},{{experience}},{{RealProject}}"



